"""Tushare 落盘字段定义。

这里故意把字段逐一列出，并在请求 Tushare 时也传入同一份字段列表。
这样上游新增字段时不会悄悄改变本地 Parquet Schema。
"""

from __future__ import annotations

import pyarrow as pa

# 下方注释中的钟点是北京时间发布时间；落盘为 Unix Epoch 微秒 int64。
VISIBLE_TIME_TYPE = pa.int64()

# visible_at：使用 trade_date，当日 16:00（收盘后）可见。
DAILY_FIELDS = (
    "ts_code",
    "trade_date",
    "open",
    "high",
    "low",
    "close",
    "pre_close",
    "change",
    "pct_chg",
    "vol",
    "amount",
)

# visible_at：使用 trade_date，当日 17:00（每日指标发布后）可见。
DAILY_BASIC_FIELDS = (
    "ts_code",
    "trade_date",
    "close",
    "turnover_rate",
    "turnover_rate_f",
    "volume_ratio",
    "pe",
    "pe_ttm",
    "pb",
    "ps",
    "ps_ttm",
    "dv_ratio",
    "dv_ttm",
    "total_share",
    "float_share",
    "free_share",
    "total_mv",
    "circ_mv",
)

# visible_at：使用 trade_date，当日 09:20 可见。
ADJ_FACTOR_FIELDS = (
    "ts_code",
    "trade_date",
    "adj_factor",
)

# visible_at：使用 trade_date，当日 09:30 可见。
SUSPEND_D_FIELDS = (
    "ts_code",
    "trade_date",
    "suspend_timing",
    "suspend_type",
)

# visible_at：使用 trade_date，当日 08:45（开盘前涨跌停价发布后）可见。
STK_LIMIT_FIELDS = (
    "trade_date",
    "ts_code",
    "up_limit",
    "down_limit",
)

# visible_at：使用 trade_date，当日 09:20（开盘前风险警示名单发布后）可见。
STOCK_ST_FIELDS = (
    "ts_code",
    "name",
    "trade_date",
    "type",
    "type_name",
)

# visible_at：使用 trade_date，当日 19:00（盘后资金流数据发布后）可见。
MONEYFLOW_FIELDS = (
    "ts_code",
    "trade_date",
    "buy_sm_vol",
    "buy_sm_amount",
    "sell_sm_vol",
    "sell_sm_amount",
    "buy_md_vol",
    "buy_md_amount",
    "sell_md_vol",
    "sell_md_amount",
    "buy_lg_vol",
    "buy_lg_amount",
    "sell_lg_vol",
    "sell_lg_amount",
    "buy_elg_vol",
    "buy_elg_amount",
    "sell_elg_vol",
    "sell_elg_amount",
    "net_mf_vol",
    "net_mf_amount",
)

# visible_at：优先使用 ann_date；缺失时依次使用 imp_ann_date、ex_date，日期结束时可见。
DIVIDEND_FIELDS = (
    "ts_code",
    "end_date",
    "ann_date",
    "div_proc",
    "stk_div",
    "stk_bo_rate",
    "stk_co_rate",
    "cash_div",
    "cash_div_tax",
    "record_date",
    "ex_date",
    "pay_date",
    "div_listdate",
    "imp_ann_date",
    "base_date",
    "base_share",
)

# visible_at：使用 ann_date，公告日结束时可见。
FORECAST_FIELDS = (
    "ts_code",
    "ann_date",
    "end_date",
    "type",
    "p_change_min",
    "p_change_max",
    "net_profit_min",
    "net_profit_max",
    "last_parent_net",
    "first_ann_date",
    "summary",
    "change_reason",
    "update_flag",
)

# visible_at：使用 ann_date，公告日结束时可见。
EXPRESS_FIELDS = (
    "ts_code",
    "ann_date",
    "end_date",
    "revenue",
    "operate_profit",
    "total_profit",
    "n_income",
    "total_assets",
    "total_hldr_eqy_exc_min_int",
    "diluted_eps",
    "diluted_roe",
    "yoy_net_profit",
    "bps",
    "perf_summary",
    "update_flag",
)

# visible_at：使用 ann_date，公告日结束时可见。
FINA_AUDIT_FIELDS = (
    "ts_code",
    "ann_date",
    "end_date",
    "audit_result",
    "audit_fees",
    "audit_agency",
    "audit_sign",
)

# visible_at：使用 cal_date，当日 00:00；交易日历属于预先公布信息。
TRADE_CAL_FIELDS = (
    "exchange",
    "cal_date",
    "is_open",
    "pretrade_date",
)

# visible_at：优先使用 f_ann_date（实际公告日），缺失时使用 ann_date，公告日结束时可见。
INCOME_FIELDS = (
    "ts_code",
    "ann_date",
    "f_ann_date",
    "end_date",
    "report_type",
    "comp_type",
    "end_type",
    "basic_eps",
    "diluted_eps",
    "total_revenue",
    "revenue",
    "int_income",
    "prem_earned",
    "comm_income",
    "n_commis_income",
    "n_oth_income",
    "n_oth_b_income",
    "prem_income",
    "out_prem",
    "une_prem_reser",
    "reins_income",
    "n_sec_tb_income",
    "n_sec_uw_income",
    "n_asset_mg_income",
    "oth_b_income",
    "fv_value_chg_gain",
    "invest_income",
    "ass_invest_income",
    "forex_gain",
    "total_cogs",
    "oper_cost",
    "int_exp",
    "comm_exp",
    "biz_tax_surchg",
    "sell_exp",
    "admin_exp",
    "fin_exp",
    "assets_impair_loss",
    "prem_refund",
    "compens_payout",
    "reser_insur_liab",
    "div_payt",
    "reins_exp",
    "oper_exp",
    "compens_payout_refu",
    "insur_reser_refu",
    "reins_cost_refund",
    "other_bus_cost",
    "operate_profit",
    "non_oper_income",
    "non_oper_exp",
    "nca_disploss",
    "total_profit",
    "income_tax",
    "n_income",
    "n_income_attr_p",
    "minority_gain",
    "oth_compr_income",
    "t_compr_income",
    "compr_inc_attr_p",
    "compr_inc_attr_m_s",
    "ebit",
    "ebitda",
    "insurance_exp",
    "undist_profit",
    "distable_profit",
    "rd_exp",
    "fin_exp_int_exp",
    "fin_exp_int_inc",
    "transfer_surplus_rese",
    "transfer_housing_imprest",
    "transfer_oth",
    "adj_lossgain",
    "withdra_legal_surplus",
    "withdra_legal_pubfund",
    "withdra_biz_devfund",
    "withdra_rese_fund",
    "withdra_oth_ersu",
    "workers_welfare",
    "distr_profit_shrhder",
    "prfshare_payable_dvd",
    "comshare_payable_dvd",
    "capit_comstock_div",
    "continued_net_profit",
    "update_flag",
)

# visible_at：优先使用 f_ann_date（实际公告日），缺失时使用 ann_date，公告日结束时可见。
BALANCESHEET_FIELDS = (
    "ts_code",
    "ann_date",
    "f_ann_date",
    "end_date",
    "report_type",
    "comp_type",
    "end_type",
    "total_share",
    "cap_rese",
    "undistr_porfit",
    "surplus_rese",
    "special_rese",
    "money_cap",
    "trad_asset",
    "notes_receiv",
    "accounts_receiv",
    "oth_receiv",
    "prepayment",
    "div_receiv",
    "int_receiv",
    "inventories",
    "amor_exp",
    "nca_within_1y",
    "sett_rsrv",
    "loanto_oth_bank_fi",
    "premium_receiv",
    "reinsur_receiv",
    "reinsur_res_receiv",
    "pur_resale_fa",
    "oth_cur_assets",
    "total_cur_assets",
    "fa_avail_for_sale",
    "htm_invest",
    "lt_eqt_invest",
    "invest_real_estate",
    "time_deposits",
    "oth_assets",
    "lt_rec",
    "fix_assets",
    "cip",
    "const_materials",
    "fixed_assets_disp",
    "produc_bio_assets",
    "oil_and_gas_assets",
    "intan_assets",
    "r_and_d",
    "goodwill",
    "lt_amor_exp",
    "defer_tax_assets",
    "decr_in_disbur",
    "oth_nca",
    "total_nca",
    "cash_reser_cb",
    "depos_in_oth_bfi",
    "prec_metals",
    "deriv_assets",
    "rr_reins_une_prem",
    "rr_reins_outstd_cla",
    "rr_reins_lins_liab",
    "rr_reins_lthins_liab",
    "refund_depos",
    "ph_pledge_loans",
    "refund_cap_depos",
    "indep_acct_assets",
    "client_depos",
    "client_prov",
    "transac_seat_fee",
    "invest_as_receiv",
    "total_assets",
    "lt_borr",
    "st_borr",
    "cb_borr",
    "depos_ib_deposits",
    "loan_oth_bank",
    "trading_fl",
    "notes_payable",
    "acct_payable",
    "adv_receipts",
    "sold_for_repur_fa",
    "comm_payable",
    "payroll_payable",
    "taxes_payable",
    "int_payable",
    "div_payable",
    "oth_payable",
    "acc_exp",
    "deferred_inc",
    "st_bonds_payable",
    "payable_to_reinsurer",
    "rsrv_insur_cont",
    "acting_trading_sec",
    "acting_uw_sec",
    "non_cur_liab_due_1y",
    "oth_cur_liab",
    "total_cur_liab",
    "bond_payable",
    "lt_payable",
    "specific_payables",
    "estimated_liab",
    "defer_tax_liab",
    "defer_inc_non_cur_liab",
    "oth_ncl",
    "total_ncl",
    "depos_oth_bfi",
    "deriv_liab",
    "depos",
    "agency_bus_liab",
    "oth_liab",
    "prem_receiv_adva",
    "depos_received",
    "ph_invest",
    "reser_une_prem",
    "reser_outstd_claims",
    "reser_lins_liab",
    "reser_lthins_liab",
    "indept_acc_liab",
    "pledge_borr",
    "indem_payable",
    "policy_div_payable",
    "total_liab",
    "treasury_share",
    "ordin_risk_reser",
    "forex_differ",
    "invest_loss_unconf",
    "minority_int",
    "total_hldr_eqy_exc_min_int",
    "total_hldr_eqy_inc_min_int",
    "total_liab_hldr_eqy",
    "lt_payroll_payable",
    "oth_comp_income",
    "oth_eqt_tools",
    "oth_eqt_tools_p_shr",
    "lending_funds",
    "acc_receivable",
    "st_fin_payable",
    "payables",
    "hfs_assets",
    "hfs_sales",
    "cost_fin_assets",
    "fair_value_fin_assets",
    "contract_assets",
    "contract_liab",
    "accounts_receiv_bill",
    "accounts_pay",
    "oth_rcv_total",
    "fix_assets_total",
    "cip_total",
    "oth_pay_total",
    "long_pay_total",
    "debt_invest",
    "oth_debt_invest",
    "update_flag",
)

# visible_at：优先使用 f_ann_date（实际公告日），缺失时使用 ann_date，公告日结束时可见。
CASHFLOW_FIELDS = (
    "ts_code",
    "ann_date",
    "f_ann_date",
    "end_date",
    "comp_type",
    "report_type",
    "end_type",
    "net_profit",
    "finan_exp",
    "c_fr_sale_sg",
    "recp_tax_rends",
    "n_depos_incr_fi",
    "n_incr_loans_cb",
    "n_inc_borr_oth_fi",
    "prem_fr_orig_contr",
    "n_incr_insured_dep",
    "n_reinsur_prem",
    "n_incr_disp_tfa",
    "ifc_cash_incr",
    "n_incr_disp_faas",
    "n_incr_loans_oth_bank",
    "n_cap_incr_repur",
    "c_fr_oth_operate_a",
    "c_inf_fr_operate_a",
    "c_paid_goods_s",
    "c_paid_to_for_empl",
    "c_paid_for_taxes",
    "n_incr_clt_loan_adv",
    "n_incr_dep_cbob",
    "c_pay_claims_orig_inco",
    "pay_handling_chrg",
    "pay_comm_insur_plcy",
    "oth_cash_pay_oper_act",
    "st_cash_out_act",
    "n_cashflow_act",
    "oth_recp_ral_inv_act",
    "c_disp_withdrwl_invest",
    "c_recp_return_invest",
    "n_recp_disp_fiolta",
    "n_recp_disp_sobu",
    "stot_inflows_inv_act",
    "c_pay_acq_const_fiolta",
    "c_paid_invest",
    "n_disp_subs_oth_biz",
    "oth_pay_ral_inv_act",
    "n_incr_pledge_loan",
    "stot_out_inv_act",
    "n_cashflow_inv_act",
    "c_recp_borrow",
    "proc_issue_bonds",
    "oth_cash_recp_ral_fnc_act",
    "stot_cash_in_fnc_act",
    "free_cashflow",
    "c_prepay_amt_borr",
    "c_pay_dist_dpcp_int_exp",
    "incl_dvd_profit_paid_sc_ms",
    "oth_cashpay_ral_fnc_act",
    "stot_cashout_fnc_act",
    "n_cash_flows_fnc_act",
    "eff_fx_flu_cash",
    "n_incr_cash_cash_equ",
    "c_cash_equ_beg_period",
    "c_cash_equ_end_period",
    "c_recp_cap_contrib",
    "incl_cash_rec_saims",
    "uncon_invest_loss",
    "prov_depr_assets",
    "depr_fa_coga_dpba",
    "amort_intang_assets",
    "lt_amort_deferred_exp",
    "decr_deferred_exp",
    "incr_acc_exp",
    "loss_disp_fiolta",
    "loss_scr_fa",
    "loss_fv_chg",
    "invest_loss",
    "decr_def_inc_tax_assets",
    "incr_def_inc_tax_liab",
    "decr_inventories",
    "decr_oper_payable",
    "incr_oper_payable",
    "others",
    "im_net_cashflow_oper_act",
    "conv_debt_into_cap",
    "conv_copbonds_due_within_1y",
    "fa_fnc_leases",
    "im_n_incr_cash_equ",
    "net_dism_capital_add",
    "net_cash_rece_sec",
    "credit_impa_loss",
    "use_right_asset_dep",
    "oth_loss_asset",
    "end_bal_cash",
    "beg_bal_cash",
    "end_bal_cash_equ",
    "beg_bal_cash_equ",
    "update_flag",
)

# visible_at：使用 ann_date，公告日结束时可见；end_date 只表示报告期，不能用于可见时间。
FINA_INDICATOR_FIELDS = (
    "ts_code",
    "ann_date",
    "end_date",
    "eps",
    "dt_eps",
    "total_revenue_ps",
    "revenue_ps",
    "capital_rese_ps",
    "surplus_rese_ps",
    "undist_profit_ps",
    "extra_item",
    "profit_dedt",
    "gross_margin",
    "current_ratio",
    "quick_ratio",
    "cash_ratio",
    "ar_turn",
    "ca_turn",
    "fa_turn",
    "assets_turn",
    "op_income",
    "ebit",
    "ebitda",
    "fcff",
    "fcfe",
    "current_exint",
    "noncurrent_exint",
    "interestdebt",
    "netdebt",
    "tangible_asset",
    "working_capital",
    "networking_capital",
    "invest_capital",
    "retained_earnings",
    "diluted2_eps",
    "bps",
    "ocfps",
    "retainedps",
    "cfps",
    "ebit_ps",
    "fcff_ps",
    "fcfe_ps",
    "netprofit_margin",
    "grossprofit_margin",
    "cogs_of_sales",
    "expense_of_sales",
    "profit_to_gr",
    "saleexp_to_gr",
    "adminexp_of_gr",
    "finaexp_of_gr",
    "impai_ttm",
    "gc_of_gr",
    "op_of_gr",
    "ebit_of_gr",
    "roe",
    "roe_waa",
    "roe_dt",
    "roa",
    "npta",
    "roic",
    "roe_yearly",
    "roa2_yearly",
    "debt_to_assets",
    "assets_to_eqt",
    "dp_assets_to_eqt",
    "ca_to_assets",
    "nca_to_assets",
    "tbassets_to_totalassets",
    "int_to_talcap",
    "eqt_to_talcapital",
    "currentdebt_to_debt",
    "longdeb_to_debt",
    "ocf_to_shortdebt",
    "debt_to_eqt",
    "eqt_to_debt",
    "eqt_to_interestdebt",
    "tangibleasset_to_debt",
    "tangasset_to_intdebt",
    "tangibleasset_to_netdebt",
    "ocf_to_debt",
    "turn_days",
    "roa_yearly",
    "roa_dp",
    "fixed_assets",
    "profit_to_op",
    "q_saleexp_to_gr",
    "q_gc_to_gr",
    "q_roe",
    "q_dt_roe",
    "q_npta",
    "q_ocf_to_sales",
    "basic_eps_yoy",
    "dt_eps_yoy",
    "cfps_yoy",
    "op_yoy",
    "ebt_yoy",
    "netprofit_yoy",
    "dt_netprofit_yoy",
    "ocf_yoy",
    "roe_yoy",
    "bps_yoy",
    "assets_yoy",
    "eqt_yoy",
    "tr_yoy",
    "or_yoy",
    "q_sales_yoy",
    "q_op_qoq",
    "equity_yoy",
)

# visible_at：原始 in_date/out_date 分别生成 IN/OUT 事件，使用对应事件日的 09:00。
INDEX_MEMBER_ALL_FIELDS = (
    "l1_code",
    "l1_name",
    "l2_code",
    "l2_name",
    "l3_code",
    "l3_name",
    "ts_code",
    "name",
    "in_date",
    "out_date",
    "is_new",
)

DATE_FIELDS = {
    "trade_date",
    "end_date",
    "ann_date",
    "f_ann_date",
    "record_date",
    "ex_date",
    "pay_date",
    "div_listdate",
    "imp_ann_date",
    "base_date",
    "first_ann_date",
}

STRING_FIELDS = {
    "ts_code",
    "report_type",
    "comp_type",
    "end_type",
    "update_flag",
    "suspend_timing",
    "suspend_type",
    "div_proc",
    "name",
    "type",
    "type_name",
    "summary",
    "change_reason",
    "perf_summary",
    "audit_result",
    "audit_agency",
    "audit_sign",
}


def _source_schema(fields: tuple[str, ...]) -> pa.Schema:
    """把固定的 Tushare 字段表转换为固定 Arrow Schema。"""
    arrow_fields: list[pa.Field[pa.DataType]] = [
        pa.field("ts_code", pa.string(), nullable=False),
        pa.field("visible_at", VISIBLE_TIME_TYPE, nullable=False),
    ]
    for name in fields:
        if name == "ts_code":
            continue
        if name in DATE_FIELDS:
            data_type = pa.date32()
        elif name in STRING_FIELDS:
            data_type = pa.string()
        else:
            data_type = pa.float64()
        arrow_fields.append(pa.field(name, data_type))
    return pa.schema(arrow_fields)


DAILY_SCHEMA = _source_schema(DAILY_FIELDS)
DAILY_BASIC_SCHEMA = _source_schema(DAILY_BASIC_FIELDS)
ADJ_FACTOR_SCHEMA = _source_schema(ADJ_FACTOR_FIELDS)
SUSPEND_D_SCHEMA = _source_schema(SUSPEND_D_FIELDS)
STK_LIMIT_SCHEMA = _source_schema(STK_LIMIT_FIELDS)
STOCK_ST_SCHEMA = _source_schema(STOCK_ST_FIELDS)
MONEYFLOW_SCHEMA = _source_schema(MONEYFLOW_FIELDS)
DIVIDEND_SCHEMA = _source_schema(DIVIDEND_FIELDS)
FORECAST_SCHEMA = _source_schema(FORECAST_FIELDS)
EXPRESS_SCHEMA = _source_schema(EXPRESS_FIELDS)
FINA_AUDIT_SCHEMA = _source_schema(FINA_AUDIT_FIELDS)
INCOME_SCHEMA = _source_schema(INCOME_FIELDS)
BALANCESHEET_SCHEMA = _source_schema(BALANCESHEET_FIELDS)
CASHFLOW_SCHEMA = _source_schema(CASHFLOW_FIELDS)
FINA_INDICATOR_SCHEMA = _source_schema(FINA_INDICATOR_FIELDS)

# 申万行业成员数据拆成 IN/OUT 事件。若把当前接口返回的未来 out_date 直接放在
# in_date 那一行，历史回测会提前知道股票将在哪一天被移出行业。
SW_INDUSTRY_SCHEMA = pa.schema(
    [
        pa.field("ts_code", pa.string(), nullable=False),
        pa.field("visible_at", VISIBLE_TIME_TYPE, nullable=False),
        pa.field("event_date", pa.date32(), nullable=False),
        pa.field("event_type", pa.string(), nullable=False),
        pa.field("l1_code", pa.string()),
        pa.field("l1_name", pa.string()),
        pa.field("l2_code", pa.string()),
        pa.field("l2_name", pa.string()),
        pa.field("l3_code", pa.string()),
        pa.field("l3_name", pa.string()),
        pa.field("stock_name", pa.string()),
    ]
)

TRADE_CAL_SCHEMA = pa.schema(
    [
        pa.field("exchange", pa.string(), nullable=False),
        pa.field("visible_at", VISIBLE_TIME_TYPE, nullable=False),
        pa.field("cal_date", pa.date32(), nullable=False),
        pa.field("is_open", pa.int8(), nullable=False),
        pa.field("pretrade_date", pa.date32()),
    ]
)

# visible_at：该覆盖区间成功写入元数据的系统时刻，Unix Epoch 微秒 int64。
SYNC_RANGES_SCHEMA = pa.schema(
    [
        pa.field("dataset", pa.string(), nullable=False),
        pa.field("ts_code", pa.string(), nullable=False),
        pa.field("visible_at", pa.int64(), nullable=False),
        pa.field("start_date", pa.date32(), nullable=False),
        pa.field("end_date", pa.date32(), nullable=False),
    ]
)

TABLE_SCHEMAS = {
    "daily": DAILY_SCHEMA,
    "daily_basic": DAILY_BASIC_SCHEMA,
    "adj_factor": ADJ_FACTOR_SCHEMA,
    "suspend_d": SUSPEND_D_SCHEMA,
    "stk_limit": STK_LIMIT_SCHEMA,
    "stock_st": STOCK_ST_SCHEMA,
    "moneyflow": MONEYFLOW_SCHEMA,
    "dividend": DIVIDEND_SCHEMA,
    "forecast": FORECAST_SCHEMA,
    "express": EXPRESS_SCHEMA,
    "fina_audit": FINA_AUDIT_SCHEMA,
    "income": INCOME_SCHEMA,
    "balancesheet": BALANCESHEET_SCHEMA,
    "cashflow": CASHFLOW_SCHEMA,
    "fina_indicator": FINA_INDICATOR_SCHEMA,
    "sw_industry": SW_INDUSTRY_SCHEMA,
    "trade_cal": TRADE_CAL_SCHEMA,
}

SOURCE_FIELDS = {
    "daily": DAILY_FIELDS,
    "daily_basic": DAILY_BASIC_FIELDS,
    "adj_factor": ADJ_FACTOR_FIELDS,
    "suspend_d": SUSPEND_D_FIELDS,
    "stk_limit": STK_LIMIT_FIELDS,
    "stock_st": STOCK_ST_FIELDS,
    "moneyflow": MONEYFLOW_FIELDS,
    "dividend": DIVIDEND_FIELDS,
    "forecast": FORECAST_FIELDS,
    "express": EXPRESS_FIELDS,
    "fina_audit": FINA_AUDIT_FIELDS,
    "income": INCOME_FIELDS,
    "balancesheet": BALANCESHEET_FIELDS,
    "cashflow": CASHFLOW_FIELDS,
    "fina_indicator": FINA_INDICATOR_FIELDS,
    "sw_industry": INDEX_MEMBER_ALL_FIELDS,
    "trade_cal": TRADE_CAL_FIELDS,
}

TABLE_PARTITION_BY = {
    dataset: "exchange" if dataset == "trade_cal" else "ts_code"
    for dataset in TABLE_SCHEMAS
}
